STDOUT_FILE=shellscript.log
TMP_FILE=tmp.sh
CONFIG_FILE=config.sh

RBT_DEFAULT="\033[00;37m" #Default
RBT_INFORMATIONCOLLOR="\033[01;32m" #Green
RBT_ALERTCOLLOR="\033[00;33m" #Yellow
RBT_CRITICALCOLLOR="\033[01;31m" #Red
RBT_EXTRAINFOCOLLOR="\033[01;34m" #Blue

RBT_FIGLET="Renato Tecchio"

RBT_TITLE1="ANSIBLE INSTALL - CONFIGURATION SERVER - SHELLSCRIPT"
RBT_TITLE2="renatotecchio@gmail.com"
RBT_TITLE3="https://github.com/renatotecchio/"

RBT_USERNAME=""
RBT_PASSWORD=""
RBT_HOME="/home/$RBT_USERNAME"